### ISSUE TITLE
Content Editor sans vs serif

### ISSUE THREAD

**Issue by hugobaeta** [mattmiklic/system-fonts-in-wp#1]
I noticed the content editor (TinyMCE) was also switched to the new typefaces, but it used to be a serif. I wonder if in this new approach there should be a serif stack for cases like this? Or is it intentional? There's also the change in padding, not sure how this was caused just from a font change tho, maybe it's unrelated. EDIT: I just realized the padding is probably from some theme editor styles.

Before:

![screen shot 2016-02-29 at 8 45 16 am](https://cloud.githubusercontent.com/assets/1514660/13401406/d418ca6c-dec0-11e5-949f-5362cd44b003.png)

After:

![screen shot 2016-02-29 at 8 45 27 am](https://cloud.githubusercontent.com/assets/1514660/13401404/d25be696-dec0-11e5-84df-51bd69e6578c.png)

**Comment by mattmiklic** [comment]
Hey there @hugobaeta, thanks for commenting! Is it possible that you're using a theme with editor styles enabled? In your screenshots it looks like Noto Serif in the Before, and Lato in the after. The font for the editor shouldn't be changed by this plugin (I think!) -- in my own testing, the editor is correctly inheriting the `font-family: Georgia, "Times New Roman", "Bitstream Charter", Times, serif;` declaration on line 17 in `/wp-includes/js/tinymce/skins/wordpress/wp-content.css`.

**Comment by hugobaeta** [comment]
You are absolutely correct. It was a theme that changed it... sorry about the confusion.

Here's a comparison with a theme that has no editor styles:

Before:
<img width="787" alt="screen shot 2016-03-09 at 4 45 05 pm" src="https://cloud.githubusercontent.com/assets/1514660/13655759/c2879a28-e616-11e5-8e63-c91608f58d47.png">

After:
<img width="788" alt="screen shot 2016-03-09 at 4 47 13 pm" src="https://cloud.githubusercontent.com/assets/1514660/13655762/c7b1ed8c-e616-11e5-9798-9500728320bd.png">
