### ISSUE TITLE
Missed items on Media page still showing Open Sans

### ISSUE THREAD

**Issue by hugobaeta** [mattmiklic/system-fonts-in-wp#2]
Found a couple of items on the media page that are still on open sans.
- "Bulk Select" (button)
- "No media attachments found."

As is it:

![screen shot 2016-02-29 at 8 49 10 am](https://cloud.githubusercontent.com/assets/1514660/13401576/7d816f64-dec1-11e5-92db-7b4a09bed7f9.png)

If I uncheck that font-family declaration:

![screen shot 2016-02-29 at 8 49 21 am](https://cloud.githubusercontent.com/assets/1514660/13401582/87768810-dec1-11e5-9b07-ba4053261781.png)

**Comment by mattmiklic** [comment]
Good catch! All fixed up in #3.
